name: tictoc
repository: https://github.com/Beyo-Inc/tictoc

packages:
  - packages/*

command:
  version:
    includeCommitId: true
  bootstrap:
    hooks:
      post: |
        dart pub run melos build_runner:build

scripts:
  lint:all:
    run: |
      dart pub run melos run lint:analyze && \
      dart pub run melos run lint:format
    description: Run all static analysis checks.
  lint:analyze:
    run: |
      dart pub run melos exec -- \
      dart analyze . --fatal-infos
    description: |
      Run `dart analyze` for all packages.
  lint:format:
    run: |
      dart pub run melos exec -- \
      dart format . --output=none --set-exit-if-changed
    description: |
      Run `dart format` for all packages.
  test:all:
    run: |
      dart pub run melos run test:unit
  test:unit:
    run: |
      dart pub run melos exec --depends-on="test" -- \
      dart test &&
      dart pub run melos exec --depends-on="dart_test" -- \
      dart test
    packageFilters:
      dirExists:
        - test
  build_runner:build:
    run: |
      dart pub run melos exec --depends-on="build_runner" -- \
      dart pub run build_runner build --delete-conflicting-outputs
    description: |
      Run `dart pub run build_runner watch` for all packages.
  build_runner:watch:
    run: |
      dart pub run melos build_runner:build &&
      dart pub run melos exec --depends-on="build_runner" -- \
      dart pub run build_runner watch --delete-conflicting-outputs
    description: |
      Run `dart pub run build_runner watch` for all packages.
 